bboard/urls.py
from django.urls import path

from .views import index, by_rubric
from .views import BbCreateView

app_name = 'bboard'
urlpatterns = [
	path('add/', BbCreateView.as_view(), name='add'),
	path('<int:rubric_id>/', by_rubric,name='by_rubric'),
	path('', index,name='index'),
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bboard.urls', namespace='')),
    path('admin/', admin.site.urls),
]

bboard/models.py
from django.db import models

# Create your models here.

    
class Bb(models.Model):
	title = models.CharField(max_length=50, verbose_name='TITLE')
	content = models.TextField(null=True,blank=True, verbose_name='CONTENT')
	price = models.FloatField(null=True, blank=True, verbose_name='PRICE')
	published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='PUBLISHED')

	rubric = models.ForeignKey('Rubric', null=True,on_delete=models.PROTECT, verbose_name='Rubric')

	class Meta:
		verbose_name_plural = 'Advertisments'
		verbose_name = 'Advertisment'
		ordering = ['-published']


class Rubric(models.Model):
	name = models.CharField(max_length=20,db_index=True,verbose_name='NAME')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Rubrics'
		verbose_name='Rubric'
		ordering = ['name']

bboard/forms.py
from django import forms
from django.core import validators


from .models import Bb, Rubric

class BbForm(forms.ModelForm):
	title = forms.CharField(label='Name of product',
		validators=[validators.RegexValidator(regex='^.{4,}$')],
		error_messages={'invalid':'Invalid name of your product!'})
	content = forms.CharField(label='Describe it',
		widget=forms.widgets.Textarea(attrs={
			'rows':10,
			'cols':25,
			'style':'resize:none;'}))
	price = forms.DecimalField(label='Price',decimal_places=2)
	rubric = forms.ModelChoiceField(queryset=Rubric.objects.all(),
		label='Rubric', help_text='Do not forget to choice rubric!',
		widget=forms.widgets.Select(attrs={'size':8}))
	class Meta:
		model = Bb
		fields = ('title','content','price','rubric')

bboard/views.py
from django.shortcuts import render, redirectfrom django.views.generic.edit import CreateViewfrom django.urls import reverse_lazyfrom django.forms import modelformset_factoryfrom .models import Bbfrom .models import Rubricfrom .forms import BbFormdef index(request):	bbs = Bb.objects.all()	rubrics = Rubric.objects.all()	context = {'bbs':bbs,'rubrics':rubrics}	return render(request, 'bboard/index.html', context)def by_rubric(request, rubric_id):	bbs = Bb.objects.filter(rubric=rubric_id)	rubrics = Rubric.objects.all()	current_rubric = Rubric.objects.get(pk=rubric_id)	context = {'bbs':bbs, 'rubrics':rubrics,'current_rubric':current_rubric}	return render(request, 'bboard/index.html', context)class BbCreateView(CreateView):	template_name = 'bboard/create.html'	form_class = BbForm	success_url = reverse_lazy('bboard:index')	def get_context_data(self, **kwargs):		context = super().get_context_data(**kwargs)		context['rubrics'] = Rubric.objects.all()		return context# def rubrics(request):# 	RubricFormSet = modelformset_factory(Rubric, # 		fields=(''),# 		can_delete=True)# 	if request.method == 'POST':# 		formset = RubricFormSet(request.POST)# 		if formset.is_valid():# 			formset.save()# 			return redirect('bboard:')# 	else:# 		formset = RubricFormSet()# 	context = {'formset':formset}# 	return render(request, 'bboard/index.html',context)

bboard/templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}

{% block title %}
	{{ current_rubric.name }}
{% endblock title %}

{% block content %}
	<h2>Rubric: {{ current_rubric.name }}</h2>
	{% for bb in bbs %}
		<div>
			<p>{{ bb.title }}</p>
			<p> {{ bb.content}}</p>
			<p> {{ bb.published|date:"d.m.Y H:i:s" }}</p>
		</div>
	{% endfor %}
{% endblock content %}

bboard/templates/bboard/create.html
{% extends "layout/basic.html" %}

{% block title %}
	Bill board
{% endblock title %}

{% block content %}
	<h2>Adding a advertisment</h2>
	<form method="post">
		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
			{{ hidden }}

		{% endfor %}
		{% if form.non_field_errors %}
		<ul>
			{% for error in form.non_field_errors %}
				<li><em>{{ error|escape }}</em></li>
			{% endfor %}
		</ul>				
		{% endif %}
		{% for field in form.visible_fields %}
			{% if field.errors %}
				<ul>
					{% for error in field.errors %}
						<li><em>{{ error|escape }}</em></li>
					{% endfor %}
				</ul>
			{% endif %}
			<p>{{ field.label_tag }}<br>
				{{ field }}<br>
				{{ field.help_text }}
			</p>
		{% endfor %}
		<input type="submit" value="Add">
	</form>
{% endblock content %}

bboard/templates/bboard/index.html
{% extends "layout/basic.html" %}

{% block content %}
		

	{% for bb in bbs %}
		<div class="b">
			<h2>{{ bb.title }}</h2>
			<p>{{ bb.content }}</p>
			<p>{{ bb.price }} $</p>
			<p> {{ bb.published|date:"d.m.Y H:i:s" }}</p>
			<p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}"></a>{{ bb.rubric.name }}</p>
		</div>
	{% endfor %}
{% endblock content %}

bboard/templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static "bboard/style.css" %}">
	<meta http-equiv="Content-Type" content="text/html" charset="utf-8">
	<title>{% block title %}Main{% endblock %} - bulletin board</title>
</head>
<body>
	<header>
		<h1>Advertisments</h1>
	</header>
	<nav>
		<div class="card">
			<a href="{% url 'bboard:index' %}">Main</a>
		</div>
		<div class="card">
			<a href="{% url 'bboard:add' %}">Add</a>
		</div>
		<div class="card">
			Rubrics:
			<ul>
			{% for rubric in rubrics %}
			<li><a href="{% url 'bboard:by_rubric' rubric.pk %}">{{ rubric.name }}</a></li>
			{% endfor %}
			</ul>
		</div>
	</nav>
	<section>
		{% block content %}
		
		{% endblock content %}
	</section>
</body>
</html>